kind: pipeline
type: docker
name: default

trigger:
  event:
    - tag

steps:
  - name: publish docker image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ${DRONE_REPO}
      tags: [${DRONE_TAG}, latest]